name: ntrk_mutations
channels:
  - openeye
  - rdkit
  - conda-forge
dependencies:
  - python>=3.6
  - jupyterlab
  - matplotlib
  - mdanalysis
  - nglview
  - openeye-toolkits
  - pandas
  - requests
  - rdkit
  - pip:
      - git+https://github.com/volkamerlab/dockin.git